#!/usr/bin/env python3
"""Generate include/maya/widget/markdown/engine/cm_entities_table.hpp from the
official WHATWG entities.json (CommonMark §6.2 uses the HTML5 named-entity set).

Only the `;`-terminated forms are emitted (the spec requires the trailing
semicolon for named entities). Each row is {name_without_&_or_;, utf8_bytes}.
Sorted by name for binary search at runtime.

Usage:  python3 scripts/gen_entities.py /path/to/entities.json
"""
import json, sys, os

src = sys.argv[1] if len(sys.argv) > 1 else "/tmp/entities.json"
with open(src) as f:
    data = json.load(f)

rows = []
for name, info in data.items():
    if not name.endswith(";"):
        continue
    key = name[1:-1]  # strip leading & and trailing ;
    utf8 = info["characters"].encode("utf-8")
    rows.append((key, utf8))

rows.sort(key=lambda r: r[0])

out = []
out.append("#pragma once")
out.append("// cm_entities_table.hpp — GENERATED by scripts/gen_entities.py from the")
out.append("// official WHATWG entities.json (HTML5 named character references).")
out.append("// CommonMark §6.2 resolves these to their Unicode value. Do not edit by")
out.append("// hand; re-run the generator to refresh.")
out.append("//")
out.append(f"// {len(rows)} semicolon-terminated named entities.")
out.append("")
out.append("#include <string_view>")
out.append("")
out.append("namespace maya::md_detail::engine {")
out.append("")
out.append("struct EntityRow { std::string_view name; std::string_view utf8; };")
out.append("")
out.append("// Sorted by name for binary search.")
out.append("inline constexpr EntityRow kEntities[] = {")

def cesc(b: bytes) -> str:
    s = ""
    for ch in b:
        s += f"\\x{ch:02x}"
    return s

for key, utf8 in rows:
    out.append(f'    {{"{key}", "{cesc(utf8)}"}},')

out.append("};")
out.append("")
out.append(f"inline constexpr int kEntityCount = {len(rows)};")
out.append("")
out.append("} // namespace maya::md_detail::engine")
out.append("")

dst = os.path.join(os.path.dirname(__file__), "..",
                   "include", "maya", "widget", "markdown", "engine",
                   "cm_entities_table.hpp")
dst = os.path.normpath(dst)
os.makedirs(os.path.dirname(dst), exist_ok=True)
with open(dst, "w") as f:
    f.write("\n".join(out))
print(f"wrote {dst} with {len(rows)} entities")
